server:
  port: 80
zuul:
  routes:
    matches:
      path: /posts/**
      serviceId: posts-service
    comments:
      path: /signUp/**
      serviceId: signup-service

spring:
  application:
    name: amvbox-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka